# Generated by Django 4.0.5 on 2022-06-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
