# Generated by Django 4.0.5 on 2022-07-31 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_delete_items'),
        ('user', '0005_alter_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='user.customer')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='product.product')),
            ],
        ),
    ]
