# Generated by Django 4.0.5 on 2022-07-31 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customerid',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='productid',
            new_name='product',
        ),
    ]
