# Generated by Django 4.0.5 on 2022-07-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_customerid_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
