# Generated by Django 4.0.5 on 2022-08-01 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customer_id'),
        ('product', '0004_remove_product_order'),
        ('order', '0003_remove_order_customer_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='user.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='product.product'),
            preserve_default=False,
        ),
    ]
