# Generated by Django 4.0.5 on 2022-08-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_customer_order_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_name',
            new_name='product',
        ),
    ]
