# Generated by Django 4.0.5 on 2022-08-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
