# Generated by Django 4.0.5 on 2022-08-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.IntegerField(null=True),
        ),
    ]
