# Generated by Django 4.0.5 on 2022-08-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
