# Generated by Django 4.0.5 on 2022-08-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_customer'),
        ('order', '0022_remove_order_orderid_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='cart.cart'),
        ),
    ]
